-- DO NOT PUT A TRAILING SEMICOLON IN THE LAST LINE OF THIS FILE
CREATE TABLE IF NOT EXISTS Devices (
    id INT PRIMARY KEY AUTO_INCREMENT,
    serial TEXT NOT NULL,
    name TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS Events (
    id INT PRIMARY KEY AUTO_INCREMENT,
    device_id INT UNSIGNED,
    type TEXT NOT NULL,
    alert BOOLEAN DEFAULT FALSE,
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS Datapoints (
    id INT PRIMARY KEY AUTO_INCREMENT,
    event_id INT UNSIGNED,
    sensor TEXT NOT NULL,
    value FLOAT
)