-- DO NOT PUT A TRAILING SEMICOLON IN THE LAST LINE OF THIS FILE
CREATE TABLE IF NOT EXISTS Device (
    device_id TEXT PRIMARY KEY,
    device_description TEXT NOT NULL,
    device_name TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS Events (
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    type TEXT DEFAULT 'not-specified',
    value FLOAT NOT NULL,
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    device_id TEXT DEFAULT NULL
);
CREATE TABLE IF NOT EXISTS Notifications (
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    message TEXT NOT NULL,
    is_read BOOLEAN DEFAULT FALSE,
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    device_id TEXT DEFAULT NULL
)