-- DO NOT PUT A TRAILING SEMICOLON IN THE LAST LINE OF THIS FILE
CREATE TABLE IF NOT EXISTS Device (
    device_id INTEGER PRIMARY KEY AUTO_INCREMENT,
    device_name VARCHAR(50) NOT NULL
);
CREATE TABLE IF NOT EXISTS HeartRate (
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    value FLOAT NOT NULL,
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    device_id INTEGER DEFAULT NULL
);
CREATE TABLE IF NOT EXISTS BloodOxygen (
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    value FLOAT NOT NULL,
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    device_id INTEGER DEFAULT NULL
);
CREATE TABLE IF NOT EXISTS FallEvents (
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    event_type VARCHAR(50) NOT NULL,
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    device_id INTEGER DEFAULT NULL
);
CREATE TABLE IF NOT EXISTS Notifications (
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    message VARCHAR(50) NOT NULL,
    is_read BOOLEAN DEFAULT FALSE,
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    device_id INTEGER DEFAULT NULL
)